using MAIMS.Core.Enums;

namespace MAIMS.Core.Entities;

/// <summary>
/// Hierarchical asset category. Top-level categories (Land, Buildings, etc.) have ParentId = null.
/// Each category carries its own depreciation policy so subclasses can diverge
/// (e.g., Vehicles → Heavy Vehicles with different useful life).
/// </summary>
public class AssetCategory : BaseEntity
{
    public string Name { get; set; } = string.Empty;
    public AssetCategoryType CategoryType { get; set; }
    public long? ParentId { get; set; }
    public string? DepreciationMethod { get; set; }   // "STRAIGHT_LINE" | "NONE"
    public int? UsefulLifeYears { get; set; }
    public decimal? SalvageValuePct { get; set; }

    public AssetCategory? Parent { get; set; }
    public ICollection<AssetCategory> Children { get; set; } = new List<AssetCategory>();
    public ICollection<Asset> Assets { get; set; } = new List<Asset>();
}

/// <summary>
/// Physical location. May be hierarchical (Site → Building → Floor → Room).
/// Optional GPS coordinates support future GIS integration (out of scope this phase).
/// </summary>
public class Location : BaseEntity
{
    public string Name { get; set; } = string.Empty;
    public string LocationType { get; set; } = string.Empty; // Site/Building/Floor/Room/Outdoor
    public long? ParentId { get; set; }
    public decimal? GpsLat { get; set; }
    public decimal? GpsLng { get; set; }
    public string? Address { get; set; }

    public Location? Parent { get; set; }
    public ICollection<Location> Children { get; set; } = new List<Location>();
}

/// <summary>
/// Core entity: a single fixed asset. AssetCode is the human-readable identifier
/// (e.g., PW-VEH-00042) generated by IAssetCodeGenerator.
/// Supports parent-child hierarchy (Building → HVAC → filter) via ParentAssetId.
/// </summary>
public class Asset : BaseEntity
{
    public string AssetCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public long CategoryId { get; set; }
    public long DepartmentId { get; set; }
    public long? LocationId { get; set; }
    public long? CustodianUserId { get; set; }
    public AssetStatus Status { get; set; } = AssetStatus.Planned;
    public DateTime? AcquisitionDate { get; set; }
    public decimal? AcquisitionCost { get; set; }
    public decimal? CurrentBookValue { get; set; }
    public ConditionRating ConditionRating { get; set; } = ConditionRating.Fair;
    public long? ParentAssetId { get; set; }
    public string? SerialNumber { get; set; }
    public string? FundingSource { get; set; }
    public string? BarcodePayload { get; set; }

    // Disposal fields (populated when Status >= Disposed)
    public DisposalMethod? DisposalMethod { get; set; }
    public DateTime? DisposalDate { get; set; }
    public decimal? DisposalProceeds { get; set; }
    public long? DisposalApprovedBy { get; set; }

    public AssetCategory? Category { get; set; }
    public Department? Department { get; set; }
    public Location? Location { get; set; }
    public User? Custodian { get; set; }
    public Asset? ParentAsset { get; set; }
    public ICollection<Asset> ChildAssets { get; set; } = new List<Asset>();
    public ICollection<AssetLifecycleEvent> LifecycleEvents { get; set; } = new List<AssetLifecycleEvent>();
    public ICollection<AssetAttachment> Attachments { get; set; } = new List<AssetAttachment>();
}

/// <summary>
/// Immutable lifecycle event for an asset. One row per state change, inspection, or maintenance.
/// </summary>
public class AssetLifecycleEvent : BaseEntity
{
    public long AssetId { get; set; }
    public AssetEventType EventType { get; set; }
    public DateTime EventDate { get; set; } = DateTime.UtcNow;
    public long? PerformedBy { get; set; }
    public string? Notes { get; set; }
    public AssetStatus? FromStatus { get; set; }
    public AssetStatus? ToStatus { get; set; }
    public decimal? Cost { get; set; }

    public Asset? Asset { get; set; }
}

/// <summary>
/// Document attached to an asset (purchase receipt, photo, manual, warranty).
/// Stored on disk; the DB stores a path reference.
/// </summary>
public class AssetAttachment : BaseEntity
{
    public long AssetId { get; set; }
    public string FilePath { get; set; } = string.Empty;
    public string FileType { get; set; } = string.Empty;     // mime type
    public string? OriginalFileName { get; set; }
    public long FileSizeBytes { get; set; }
    public string? Description { get; set; }

    public Asset? Asset { get; set; }
}
